{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b004b0c3_31c3e9f8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1004087
      },
      "writtenOn": "2022-11-11T14:42:15Z",
      "side": 1,
      "message": "I\u0027m confused.  I can\u0027t find any dbus exception in ganesha_stats.py.  It catches all exceptions, and exits.",
      "revId": "22aa4e20a6365c88da05217b0b517620414cc43b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bd61ff53_c966db2a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1020701
      },
      "writtenOn": "2022-11-11T15:05:01Z",
      "side": 1,
      "message": "Sorry for the confusion. I have to merge with another patch with this. I\u0027ll rework on this..\nThanks for notify me.",
      "parentUuid": "b004b0c3_31c3e9f8",
      "revId": "22aa4e20a6365c88da05217b0b517620414cc43b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "cf9c7f75_adf4e897",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1020701
      },
      "writtenOn": "2022-11-11T15:05:01Z",
      "side": 1,
      "message": "Marking as -1 for now. ",
      "revId": "22aa4e20a6365c88da05217b0b517620414cc43b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}