{
  "comments": [
    {
      "key": {
        "uuid": "885cfa58_689b4179",
        "filename": "src/include/abstract_mem.h",
        "patchSetId": 3
      },
      "lineNbr": 91,
      "author": {
        "id": 1003571
      },
      "writtenOn": "2019-01-25T17:55:12Z",
      "side": 1,
      "message": "Was there a reason for not doing the LogMallocFailure?",
      "revId": "6ea3313c44bf41736b88975b993548c6eeef4577",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "2712a62d_6cafe49f",
        "filename": "src/include/abstract_mem.h",
        "patchSetId": 3
      },
      "lineNbr": 91,
      "author": {
        "id": 1003947
      },
      "writtenOn": "2019-01-25T18:48:28Z",
      "side": 1,
      "message": "We abort() and we catch abort and log backtrace. I thought that is good enough.",
      "parentUuid": "885cfa58_689b4179",
      "revId": "6ea3313c44bf41736b88975b993548c6eeef4577",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}