{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "3e972bed_31b006e9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1003571
      },
      "writtenOn": "2021-03-11T23:40:08Z",
      "side": 1,
      "message": "Is this CI test failure an issue with the patch?",
      "revId": "842bb9a77a979ccb11fbd1bd87955f3f212e9e8d",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}